import { StyleSheet, Dimensions } from "react-native";
import { COLORS } from "../../constants";
const { width, height } = Dimensions.get('window')

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.white,
    },
    head: {
        width: width,
        height: height * .15,
        backgroundColor: COLORS.blue,
        marginTop: height * .01,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-evenly',
    },
    leftBox: {
        width: width * .45,
        height: height * .12,
        justifyContent: 'center',
    },
    rightBox: {
        width: width * .45,
        height: height * .12,
        justifyContent: 'center',
    },
    line: {
        width: width * .003,
        height: height * .12,
        backgroundColor: COLORS.white,
    },
    headTitle: {
        fontFamily: 'Poppins Medium 500',
        fontSize: 11.5,
        color: COLORS.white,
    },
    txt: {
        fontFamily: 'Poppins Regular 400',
        color: COLORS.white,
        fontSize: 8,
        marginTop: 5,
    },
    imgRow: {
        flexDirection: 'row',
        marginTop: height * .03,
        marginBottom: height * .03,
        width: width,
        height: height * .25,
    },
    image: {
        width: width ,
        justifyContent: 'center',
    },
    imgTxtContainer: {
        width: width,
        height: height * .25,
        justifyContent: 'center',
        alignItems: 'center',
    },
    imgBoxTitle: {
        fontFamily: 'Poppins Bold 700',
        fontSize: 20,
        lineHeight: 30,
        color: COLORS.white,
    },
    imgBoxSubTitle: {
        fontFamily: 'Poppins Regular 400',
        fontSize: 12,
        lineHeight: 18,
        color: COLORS.white,
    },
    categoryCartRow: {
        flexDirection: 'row',
        flexWrap:'wrap',
        justifyContent: 'space-evenly',
        alignItems: 'center',
    },
    categoryCart:{
        width: width * .45,
        height: height * .21,
        borderRadius: 10,
        overflow:'hidden',
        marginVertical: height * .01,
    },
    cartImage:{
        width: width * .45,
        height: height * .15,
        margin:0,
    },
    cartBtn:{
        height: height * .06,
        backgroundColor: COLORS.black,
        alignItems:'center',
        justifyContent: 'center',
    },
    cartBtnTxt:{
        fontFamily: 'Poppins Regular 400',
        fontSize: 12,
        color: COLORS.white,
    },
    specialTitle:{
        fontFamily: 'Poppins SemiBold 600',
        fontSize: 14,
        lineHeight: 20,
        color: COLORS.blue,
    },
    light:{
        width: width * .04,
        height: height * .03,
        marginRight: width * .03,
    },
    button:{
        width: width * .38,
        height: height * .04,
        flexDirection:'row',
        alignItems:'center',
        paddingHorizontal: width * .03,
        borderWidth: 1,
        borderColor: COLORS.blue,
        borderRadius: 6,
        marginVertical: height * .003
    },
    buttonText:{
        fontFamily: 'Poppins Regular 400',
        fontSize: 10,
        lineHeight:14,
        color: COLORS.white,
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        marginTop: height * .02,
        marginBottom: height * .02,
    },
    categoryTxt: {
        color: COLORS.black,
        fontFamily: 'Poppins Regular 400',
        fontSize: 16,
        marginBottom: -5,
        textAlign: 'center',
    },
    categoryBox: {
        width: width * .2,
        height: height * .007,
        backgroundColor: COLORS.blue,
    },
    arrivalsImg: {
        width: width,
        height: height * .25,
        padding: width * .03,
        marginTop: height * .02,
        marginBottom: height * .02, 
    },
    shopNowBtn: {
        width: width * .34,
        height: height * .05,
        position:'absolute',
        bottom: height * .02,
        left: width * .03,
        backgroundColor: COLORS.black2,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 6,
        marginTop: height * .012,
        shadowColor: COLORS.blue,
        elevation:10,
    },
    shopNowTxt: {
        fontFamily: 'Poppins SemiBold 600',
        fontSize: 15,
        lineHeight: 20,
        color: COLORS.white,
    },
    categoryName: {
        width: width * .22,
        height: height * .026,
        borderColor: 'rgba(0, 0, 0, 0.2)',
        borderWidth: 1,
        borderRadius: 31,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: width * .005,
        marginRight: width * .005,
    },
    categoryNameTxt: {
        color: COLORS.black,
        fontFamily: 'Poppins Regular 400',
        fontSize: 8,
        marginBottom: -1,
        textAlign: 'center',
    },
    rowCategory: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        marginRight: width * .02,
    },
    viewAllTxt: {
        color: COLORS.blue,
        fontFamily: 'Poppins SemiBold 600',
        fontSize: 12,
        marginBottom: -3,
        textAlign: 'center',
    },


})